### ISSUE TITLE
Why fork?

### ISSUE THREAD

**Issue by langston-barrett** [JasonGross/proviola-source#2]
Hi, I was just wondering about the difference between this project and the upstream. Could you clarify that a little bit? Might be good information for the README.

**Comment by JasonGross** [comment]
I forked because the released version was insufficient for my needs and, if I recall correctly, the newer version on bitbucket used a Python library that was incompatible with Coq's questionable practice of using non UTF-8 code points.  So I took the released version and fixed an issue with `..` and added some more notation handling... there are only 8 commits and only four of them make semantic modifications, so I don't expect the differences to be too hard to track down.  I'm not particularly interested in updating the README of this basically inactive repo, but if you make a pull request, I'll probably merge it.

**Comment by siddharthist** [comment]
@JasonGross Thanks for the info!
